<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>FoodUnlock</AssemblyName>
    <Version>0.3.2</Version>
    <LangVersion>latest</LangVersion>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GameDir Condition="'$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</GameDir>
    <ProfileDir Condition="'$(ProfileDir)' == ''">$(APPDATA)\r2modmanPlus-local\Valheim\profiles\Default</ProfileDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(GameDir)\valheim_Data\Managed\assembly_valheim.dll" Private="false" />
    <Reference Include="$(GameDir)\valheim_Data\Managed\assembly_utils.dll" Private="false" />
    <Reference Include="$(GameDir)\valheim_Data\Managed\assembly_guiutils.dll" Private="false" />
    <Reference Include="$(GameDir)\valheim_Data\Managed\UnityEngine*.dll" Private="false" />
    <Reference Include="$(ProfileDir)\BepInEx\core\BepInEx.dll" Private="false" />
    <Reference Include="$(ProfileDir)\BepInEx\core\0Harmony.dll" Private="false" />
    <Reference Include="$(ProfileDir)\BepInEx\plugins\ValheimModding-Jotunn\Jotunn.dll" Private="false" />
  </ItemGroup>
</Project>
